name: VPS Dispatch Handler

on:
  repository_dispatch:
    types: [vps-summary-ready]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge
        run: |
          echo "Triggered by VPS dispatch: ${{ github.event.client_payload.message }}"